package dev.sasha.clauderemarks.action

import com.intellij.ide.actions.ActivateToolWindowAction
import com.intellij.openapi.actionSystem.ActionManager
import com.intellij.testFramework.fixtures.BasePlatformTestCase

/**
 * These three ids are a public interface. They are what a .ideavimrc maps with ":action <id>", and
 * they are documented in the README as ids that will not be renamed. A rename would break every
 * user's mapping silently: ":action" on an unknown id fails inside IdeaVim, not here, so nothing in
 * this project would ever notice.
 */
class ActionIdsTest : BasePlatformTestCase() {

    fun testTheRegisteredActionIdsAreTheDocumentedOnes() {
        val manager = ActionManager.getInstance()
        assertNotNull("ClaudeRemarks.AddRemark is documented in the README", manager.getAction("ClaudeRemarks.AddRemark"))
        assertNotNull("ClaudeRemarks.CopyAll is documented in the README", manager.getAction("ClaudeRemarks.CopyAll"))
    }

    /**
     * The tool window's activation action is generated by the platform from the tool window id in
     * plugin.xml, so it is not written down anywhere in Kotlin. Renaming <toolWindow id="Claude
     * Remarks"> silently changes the id the README publishes. This asserts the derivation, so at
     * least the documented string is checked against the rule that produces it.
     */
    fun testTheToolWindowActivationIdIsTheDocumentedOne() {
        assertEquals(
            "ActivateClaudeRemarksToolWindow",
            ActivateToolWindowAction.Manager.getActionIdForToolWindow("Claude Remarks"),
        )
    }
}
