package dev.sasha.clauderemarks.action

import com.intellij.ide.actions.ActivateToolWindowAction
import com.intellij.openapi.actionSystem.ActionManager
import com.intellij.openapi.wm.ToolWindowEP
import com.intellij.testFramework.fixtures.BasePlatformTestCase
import dev.sasha.clauderemarks.ui.RemarksToolWindowFactory

/**
 * These three ids are a public interface. They are what a .ideavimrc maps with ":action <id>", and
 * they are documented in the README as ids that will not be renamed. A rename would break every
 * user's mapping silently: ":action" on an unknown id fails inside IdeaVim, not here, so nothing in
 * this project would ever notice.
 */
class ActionIdsTest : BasePlatformTestCase() {

    fun testTheRegisteredActionIdsAreTheDocumentedOnes() {
        val manager = ActionManager.getInstance()
        assertNotNull("ClaudeRemarks.AddRemark is documented in the README", manager.getAction("ClaudeRemarks.AddRemark"))
        assertNotNull("ClaudeRemarks.CopyAll is documented in the README", manager.getAction("ClaudeRemarks.CopyAll"))
    }

    /**
     * The third control that used to answer a waiting review. Phase 10 deleted the action class and
     * its registration, because publishing is now the only way to answer one. Nothing else notices a
     * dead registration coming back: an action nobody can reach still loads without complaint.
     */
    fun testTheSendToWaitingActionIsGone() {
        assertNull(
            "ClaudeRemarks.SendToWaiting was removed in phase 10: a publish answers a waiting review",
            ActionManager.getInstance().getAction("ClaudeRemarks.SendToWaiting"),
        )
    }

    /**
     * The id ClaudeRemarks.CopyAll cannot show the rename from Copy to Publish — renaming the id
     * would break every .ideavimrc mapping to it silently — so this pins the rename the id itself
     * cannot show: the label the person sees starts with "Publish".
     */
    fun testClaudeRemarksCopyAllsLabelStartsWithPublish() {
        val action = ActionManager.getInstance().getAction("ClaudeRemarks.CopyAll")
        assertNotNull("ClaudeRemarks.CopyAll is registered", action)
        val text = action!!.templatePresentation.text
        assertTrue(
            "expected the template text to start with \"Publish\", was \"$text\"",
            text != null && text.startsWith("Publish"),
        )
    }

    /**
     * The tool window's activation action is generated by the platform from the tool window id in
     * plugin.xml, so it is not written down anywhere in Kotlin. Renaming <toolWindow id="Claude
     * Remarks"> silently changes the id the README publishes.
     *
     * The id is read out of the real registration rather than typed here, which is the whole point:
     * with both sides hardcoded this only tested platform code, and the rename it worries about left
     * it green. ToolWindowEP is the extension point behind <toolWindow>, and ToolWindowManager cannot
     * stand in for it — the headless manager a light fixture provides only knows tool windows that
     * something registered by hand.
     */
    fun testTheToolWindowActivationIdIsTheDocumentedOne() {
        val registered = ToolWindowEP.EP_NAME.extensionList
            .single { it.factoryClass == RemarksToolWindowFactory::class.java.name }

        assertEquals("Claude Remarks", registered.id)
        assertEquals(
            "ActivateClaudeRemarksToolWindow",
            ActivateToolWindowAction.Manager.getActionIdForToolWindow(registered.id),
        )
    }
}
